### ISSUE TITLE
Shows me this error ! Anyway to fix this?

### ISSUE THREAD

**Issue by memidhun** [GitSquared/edex-ui#1003]
kali@kali:~/Downloads$ ./eDEX-UI-Linux-arm64.AppImage 
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/kali/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-U2vMQfV/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-U2vMQfV/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-U2vMQfV/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-U2vMQfV/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-U2vMQfV/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-U2vMQfV/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-U2vMQfV/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-U2vMQfV/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-U2vMQfV/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:7971) UnhandledPromiseRejectionWarning: Error: /tmp/.org.chromium.Chromium.QeWvsV: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-U2vMQfV/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:7971) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7971) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wrac4242** [comment]
which OS are you using
and which version of edex

**Comment by parkerlreed** [comment]
Based on the output, Linux on an ARM64 device running 2.2.5

**Comment by wrac4242** [comment]
and yea, it looks like kali linux, which has on the wiki `do not expect to be able to add random unrelated packages and repositories that are "out of band" of the regular Kali software sources and have it Just Work.`
 so it might just be kali

**Comment by terminalforlife** [comment]
I'm on an Ubuntu-based setup and I appear to be getting the same output from the v2.2.5 AppImage. Will not load.

**Comment by philclifford** [comment]
similar problem on Ubuntu 18.04 on x86_64:
-------
~/Downloads$ ./eDEX-UI-Linux-x86_64-2.2.5.AppImage
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/phil/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3090
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:94163) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.dLp65t)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UIWTw4Q/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
---------
prior version was working fine  but now also has (different) errors:
-----------------
~/Downloads$ ./eDEX-UI-Linux-x86_64.AppImage 
▶  start     Starting eDEX-UI v2.2.3
ℹ  info      With Node 12.16.3 and Electron 10.1.6
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/phil/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3090
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
ℹ  info      Multithread worker started at 98514
ℹ  info      Multithread worker started at 98508
ℹ  info      Multithread worker started at 98509
ℹ  info      Multithread worker started at 98515
ℹ  info      Multithread worker started at 98516
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 98517
ℹ  info      Multithread worker started at 98518
[98403:0120/143813.834747:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_OPERATION: Framebuffer is incomplete.
[98403:0120/143813.835278:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_OPERATION: Framebuffer is incomplete.
[98403:0120/143813.838867:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[98403:0120/143813.839056:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[98403:0120/143813.989463:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[98403:0120/143813.989690:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[98403:0120/143814.057343:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   Connected to frontend!
◼  Startup   Timer run for: 12.43s
ℹ  info      Resized TTY to  155 029
ℹ  info      UpdateChecker: New version v2.2.5 available.
✖  error     Error: ENOENT, node_modules/geolite2-redist/dbs-tmp/GeoLite2-Country.mmdb not found in /tmp/.mount_eDEX-UGpFvgw/resources/app.asar: Uncaught Error: ENOENT, node_modules/geolite2-redist/dbs-tmp/GeoLite2-Country.mmdb not found in /tmp/.mount_eDEX-UGpFvgw/resources/app.asar
⬤  debug     at events.js 287:7
✖  error     Error: ENOENT, node_modules/geolite2-redist/dbs-tmp/GeoLite2-ASN.mmdb not found in /tmp/.mount_eDEX-UGpFvgw/resources/app.asar: Uncaught Error: ENOENT, node_modules/geolite2-redist/dbs-tmp/GeoLite2-ASN.mmdb not found in /tmp/.mount_eDEX-UGpFvgw/resources/app.asar
⬤  debug     at events.js 287:7
✖  error     Error: ENOENT, node_modules/geolite2-redist/dbs-tmp/GeoLite2-City.mmdb not found in /tmp/.mount_eDEX-UGpFvgw/resources/app.asar: Uncaught Error: ENOENT, node_modules/geolite2-redist/dbs-tmp/GeoLite2-City.mmdb not found in /tmp/.mount_eDEX-UGpFvgw/resources/app.asar
⬤  debug     at events.js 287:7

(edex-ui:98312): Gdk-WARNING **: 14:39:05.986: gdk_window_set_user_time called on non-toplevel

☐  pending   Creating new TTY process on port 3092
✔  success   New terminal back-end initialized at 3092
✔  success   TTY 3092 connected to frontend (process PID 47580)
[98403:0120/143921.794952:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
☐  pending   Creating new TTY process on port 3093
✔  success   New terminal back-end initialized at 3093
✔  success   TTY 3093 connected to frontend (process PID 48894)
[98403:0120/143923.215150:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x7b0b76ac00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.

(edex-ui:98312): Gdk-WARNING **: 14:39:58.592: gdk_window_set_user_time called on non-toplevel


(edex-ui:98312): Gdk-WARNING **: 14:40:00.776: gdk_window_set_user_time called on non-toplevel


(edex-ui:98312): Gdk-WARNING **: 14:40:01.624: gdk_window_set_user_time called on non-toplevel


(edex-ui:98312): Gdk-WARNING **: 14:40:01.832: gdk_window_set_user_time called on non-toplevel


(edex-ui:98312): Gdk-WARNING **: 14:40:01.944: gdk_window_set_user_time called on non-toplevel


(edex-ui:98312): Gdk-WARNING **: 14:40:02.912: gdk_window_set_user_time called on non-toplevel

--------------

tried building from source but that also failed: after a few bangs against the wall to get the distro node version out of the way and the snap in place it built ok and looked very promising until a big blank white box overlaid the UI and the following error was left on exiting:
----
~/src/edex-ui/dist$ ./eDEX-UI-Linux-x86_64.AppImage
▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/phil/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3090
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
ℹ  info      Multithread worker started at 43451
ℹ  info      Multithread worker started at 43456
ℹ  info      Multithread worker started at 43458
ℹ  info      Multithread worker started at 43457
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 43460
ℹ  info      Multithread worker started at 43468
ℹ  info      Multithread worker started at 43465
[43345:0121/003805.312148:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x2c035c5c8100] GL_INVALID_OPERATION: Framebuffer is incomplete.
[43345:0121/003805.314095:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x2c035c5c8100] GL_INVALID_OPERATION: Framebuffer is incomplete.
[43345:0121/003805.319479:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x2c035c5c8100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[43345:0121/003805.319622:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x2c035c5c8100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[43345:0121/003805.381898:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x2c035c5c8100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[43345:0121/003805.382047:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x2c035c5c8100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   Connected to frontend!
◼  Startup   Timer run for: 12.41s
[43345:0121/003805.548521:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x2c035c5c8100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
ℹ  info      Resized TTY to  155 031
ℹ  info      UpdateChecker: Running an unreleased, development version.
✖  error     Error: ENOENT: no such file or directory, rename '/home/phil/.config/eDEX-UI/geoIPcache-tmp' -> '/home/phil/.config/eDEX-UI/geoIPcache': Uncaught Error: ENOENT: no such file or directory, rename '/home/phil/.config/eDEX-UI/geoIPcache-tmp' -> '/home/phil/.config/eDEX-UI/geoIPcache'
⬤  debug     at /tmp/.mount_eDEX-Ubq14Il/resources/app.asar/node_modules/geolite2-redist/index.js 1:1570

(edex-ui:43283): Gdk-WARNING **: 00:38:27.526: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:38:27.578: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:38:27.665: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:38:28.089: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:38:33.706: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:38:33.834: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:38:33.962: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:38:34.154: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:39:12.839: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:39:14.247: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:39:14.583: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:39:14.815: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:39:14.935: gdk_window_set_user_time called on non-toplevel


(edex-ui:43283): Gdk-WARNING **: 00:39:16.471: gdk_window_set_user_time called on non-toplevel

☒  complete  Terminal exited { exitCode: 0, signal: 0 } undefined
☒  complete  Shutting down...
-------
Hope some of that might help, or elicit a suggestion or two to try and fix.

**Comment by GitSquared** [comment]
`node-pty` related errors are often linked to a wrong binary/host architecture match. On `arm`, there are a multitude of sub-architectures which we may not support (I believe the current binaries are targeted for arm64v8).

**Comment by GitSquared** [comment]
(@philclifford see #1011)
