### ISSUE TITLE
Error when running.

### ISSUE THREAD

**Issue by messengeroflight** [GitSquared/edex-ui#1011]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here. Screenshots and step-by-step instructions can help a lot!)

I tried running the program, and it wouldn't run. I got this instead:

```
ash@LightBox:~$ ./eDEX-UI-Linux-x86_64.AppImage 
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/ash/.config/eDEX-UI
☐  pending   Mirroring internal assets...

(edex-ui:799): Gtk-WARNING **: 00:16:27.936: Theme parsing error: gtk.css:597:14: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.936: Theme parsing error: gtk.css:597:14: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.936: Theme parsing error: gtk.css:600:17: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.938: Theme parsing error: gtk.css:784:14: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.938: Theme parsing error: gtk.css:784:14: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.938: Theme parsing error: gtk.css:787:17: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.939: Theme parsing error: gtk.css:1096:14: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.939: Theme parsing error: gtk.css:1096:14: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.940: Theme parsing error: gtk.css:1099:17: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.945: Theme parsing error: gtk.css:2286:8: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.945: Theme parsing error: gtk.css:2286:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(edex-ui:799): Gtk-WARNING **: 00:16:27.945: Theme parsing error: gtk.css:2291:8: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.945: Theme parsing error: gtk.css:2291:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4357:14: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4357:14: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4419:12: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4419:12: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4428:16: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4428:16: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4443:22: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.952: Theme parsing error: gtk.css:4443:22: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.953: Theme parsing error: gtk.css:4499:12: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.953: Theme parsing error: gtk.css:4501:16: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.953: Theme parsing error: gtk.css:4501:16: Expected a string.

(edex-ui:799): Gtk-WARNING **: 00:16:27.953: Theme parsing error: gtk.css:4549:12: not a number

(edex-ui:799): Gtk-WARNING **: 00:16:27.953: Theme parsing error: gtk.css:4549:12: Expected a string.
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-UKRu0oX/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-UKRu0oX/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-UKRu0oX/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-UKRu0oX/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UKRu0oX/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-UKRu0oX/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-UKRu0oX/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-UKRu0oX/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-UKRu0oX/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:799) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.Gto65Q)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UKRu0oX/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:799) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:799) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by GitSquared** [comment]
> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.Gto65Q)

You should look into install libc 2.28 on your distro.
