### ISSUE TITLE
Can not run E-DEX on Elementary OS.

### ISSUE THREAD

**Issue by chobotnice007** [GitSquared/edex-ui#1022]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I decided to install E-DEX-UI on Elementary OS. I am running Elementary OS 5.1.7 Hera which is based on Ubuntu 18.04.4 LTS. I downloaded the latest. AppImage and set up permission for executing for me. I run E-DEX but nothing displayed. The process is still running. I don't know how to fix that.

**Comment by wrac4242** [comment]
hey, can you try building from source, just to see if its an issue in the appimage

**Comment by chobotnice007** [comment]
> hey, can you try building from source, just to see if its an issue in the appimage

I tried by it failed. Npm have problem with installing dependencies.

**Comment by wrac4242** [comment]
can you send the log / output of the failing part

**Comment by chobotnice007** [comment]
> can you send the log / output of the failing part

Yes
`chobotnice@Tomas-Linux:~/eDEX-UI$ ./eDEX-UI-Linux-x86_64.AppImage
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/chobotnice/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-UFLgqfz/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-UFLgqfz/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-UFLgqfz/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-UFLgqfz/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UFLgqfz/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-UFLgqfz/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-UFLgqfz/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-UFLgqfz/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-UFLgqfz/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:17421) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.leX933)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UFLgqfz/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:17421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by wrac4242** [comment]
see #997, same issue

**Comment by chobotnice007** [comment]
I can not find this dependence `GLIBC_2.28`.

**Comment by wrac4242** [comment]
i believe it is included in the build essentials package, however you may need to refer to some of the messages in #997 if you are still having issues
