### ISSUE TITLE
Error on startup: Module not found

### ISSUE THREAD

**Issue by patchicsd** [GitSquared/edex-ui#1094]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [x] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x ] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

Greetings, I am using a ubuntu 18.04.2 x86_64 machine and i downloaded the corresponding 2.2.7 release.
After i chmod the appimage i run it and i get the following terminal output:

▶  start     Starting eDEX-UI v2.2.7
ℹ  info      With Node 12.18.3 and Electron 11.3.0
ℹ  info      Renderer is Chrome 87.0.4280.141
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/patchi/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:16000) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.WGSXgk)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-Ur1CxBR/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
(node:16000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'd like to notice that libc6 is already installed and updated. Thank you for your time and im looking forward to using this emulator.

**Comment by wrac4242** [comment]
issue is with the verstion of libc, it is looking for version 2.28, as described in #1011

**Comment by GitSquared** [comment]
<img align="right" width="150" src="https://user-images.githubusercontent.com/24496417/112365822-61689300-8cd8-11eb-8faf-60e5335e5dc8.png"/>


Getting a libc upgrade on ubuntu 18.04 is going to be a pain, but if you can, you should consider upgrading to ubuntu 20.04, the latest LTS (long term support) version.

See attached image for a helpful list of ubuntu versions and their codenames - you're lagging one LTS release behind. The libc version bundled with 20.04 is 2.31, which should let you run edex with no issues.

Running `update-manager -c` in a terminal should get you a graphical prompt to begin the upgrade process.
