### ISSUE TITLE
Regarding:   #1134

### ISSUE THREAD

**Issue by davidjsullivan8** [GitSquared/edex-ui#1139]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [ X] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ X] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [X ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

I'm unable to add additional comments to #1134.
I opened the config file:  
file:///home/david/.local/share/applications/appimagekit-edex-ui.desktop
with Gedit and changed Terminal from false to True:
[Desktop Entry]
Name=eDEX-UI
Comment=eDEX-UI sci-fi interface
Exec="/home/david/eDEX-UI.Linux.x86_64.AppImage" %U
Terminal=true
Type=Application
Icon=appimagekit-edex-ui
StartupWMClass=eDEX-UI
X-AppImage-Version=2.2.2.1702
Categories=System;
X-AppImage-BuildId=1LSbIGfaJgjbUvMW2DgU2trL8r0
X-Desktop-File-Install-Version=0.24
X-AppImage-Comment=Generated by /tmp/.mount_eDEX-UJr2D9i/AppRun
TryExec=/home/david/eDEX-UI.Linux.x86_64.AppImage

I then rebooted and launched eDex.
Got the following reply from terminal:
e▶  start     Starting eDEX-UI v2.2.2
ℹ  info      With Node 10.11.0 and Electron 4.2.0
ℹ  info      Renderer is Chrome 69.0.3497.128
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/david/.config/eDEX-UI
dex☐  pending   Loading settings file...
✔  success   Settings loaded!
(node:8155) UnhandledPromiseRejectionWarning: Error: Command failed: terminator -ilc echo -n "_SHELL_ENV_DELIMITER_"; env; echo -n "_SHELL_ENV_DELIMITER_"; exit
Usage: terminator [options]

terminator: error: Additional unexpected arguments found: ['echo -n "_SHELL_ENV_DELIMITER_"; env; echo -n "_SHELL_ENV_DELIMITER_"; exit']

    at makeError (/tmp/.mount_eDEX-UiKQ53N/resources/app.asar/node_modules/shell-env/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/tmp/.mount_eDEX-UiKQ53N/resources/app.asar/node_modules/shell-env/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![image](https://user-images.githubusercontent.com/70658144/124365860-e38e1f00-dc18-11eb-8e63-8c12745b0d1b.png)

Do you have any further recommendations?  Thanks so much for the help.

**Comment by GitSquared** [comment]
This is from here: https://github.com/GitSquared/edex-ui/blob/c5f1948f86e6913a3c62fcfc957c3c33da231352/src/_boot.js#L234

[sindresorhus/shell-env](https://github.com/sindresorhus/shell-env) is a little tool that tries running a command with the shell it's provided to get what your env vars are in that environment:

https://github.com/sindresorhus/shell-env/blob/b60d531b00194e1edd6399d7a25757ea90aa5916/index.js#L6-L9

You seem to have set Terminator as the `shell` option for eDEX, but Terminator is not a shell, it is a terminal emulator (like edex itself). This is why it doesn't understand the flags shell-env tries to feed it.

You should set a shell in edex options. Examples of shell includes bash, zsh, fish, and many more - if you're unsure what to pick, bash is the default in many distros including ubuntu.

**Comment by rajkumarraiyan** [comment]
Thanks

**Comment by davidjsullivan8** [comment]
You are correct.  I made the mistake of changing the shell from bash to Terminator.  I can't access the settings to change it back.  I'd love to change it back to bash, but I don't know how to do it.  Apologies.  I have zero programming skills.  Thanks for the help.

**Comment by Animus-Surge** [comment]
If you navigate to the `~/.local/share` folder either in bash or in the file browser, there should be a folder called `edex-ui` (or something of the sort). In there should be the `settings.json` file, in which you can change the terminal back to bash.

**Comment by GitSquared** [comment]
That's right! But on Linux, you should look in `~/.config`.
