### ISSUE TITLE
Cannot launch on Elementary OS Installed on virtaul box

### ISSUE THREAD

**Issue by lZzozZl** [GitSquared/edex-ui#295]
> pm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! edex-ui@1.1.0 start: `electron src`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the edex-ui@1.1.0 start script 'electron src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the edex-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs edex-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls edex-ui
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/zzozz/Desctop/TronTerminal/edex-ui/npm-debug.log

----

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
> 2 info using npm@3.5.2
> 3 info using node@v8.10.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle edex-ui@1.1.0~prestart: edex-ui@1.1.0
> 6 silly lifecycle edex-ui@1.1.0~prestart: no script for prestart, continuing
> 7 info lifecycle edex-ui@1.1.0~start: edex-ui@1.1.0
> 8 verbose lifecycle edex-ui@1.1.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle edex-ui@1.1.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/zzozz/Desctop/TronTerminal/edex-ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> 10 verbose lifecycle edex-ui@1.1.0~start: CWD: /home/zzozz/Desctop/TronTerminal/edex-ui
> 11 silly lifecycle edex-ui@1.1.0~start: Args: [ '-c', 'electron src' ]
> 12 info lifecycle edex-ui@1.1.0~start: Failed to exec start script
> 13 verbose stack Error: edex-ui@1.1.0 start: `electron src`
> 13 verbose stack spawn ENOENT
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid edex-ui@1.1.0
> 15 verbose cwd /home/zzozz/Desctop/TronTerminal/edex-ui
> 16 error Linux 4.15.0-39-generic
> 17 error argv "/usr/bin/node" "/usr/bin/npm" "start"
> 18 error node v8.10.0
> 19 error npm  v3.5.2
> 20 error file sh
> 21 error code ELIFECYCLE
> 22 error errno ENOENT
> 23 error syscall spawn
> 24 error edex-ui@1.1.0 start: `electron src`
> 24 error spawn ENOENT
> 25 error Failed at the edex-ui@1.1.0 start script 'electron src'.
> 25 error Make sure you have the latest version of node.js and npm installed.
> 25 error If you do, this is most likely a problem with the edex-ui package,
> 25 error not with npm itself.
> 25 error Tell the author that this fails on your system:
> 25 error     electron src
> 25 error You can get information on how to open an issue for this project with:
> 25 error     npm bugs edex-ui
> 25 error Or if that isn't available, you can get their info via:
> 25 error     npm owner ls edex-ui
> 25 error There is likely additional logging output above.
> 26 verbose exit [ 1, true ]
>

**Comment by lZzozZl** [comment]
> zzozz@zzozz-ElementaryBox:~/Desctop/TronTerminal/edex-ui$ node -v
> v8.10.0
> zzozz@zzozz-ElementaryBox:~/Desctop/TronTerminal/edex-ui$ npm -v
> 6.4.1
