### ISSUE TITLE
Cannot build on ubuntu 18.10

### ISSUE THREAD

**Issue by phiter** [GitSquared/edex-ui#362]
I am unable to execute `npm run build-linux` properly on my OS.

![image](https://user-images.githubusercontent.com/12252332/50397896-87e69f00-075a-11e9-9aa5-d25462b0fc2e.png)

This is the error I'm getting:

```
> node-pty@0.8.0 install /home/phiter/edex-ui/prebuild-src/node_modules/node-pty
> node scripts/install.js

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/phiter/edex-ui/prebuild-src/node_modules/node-pty/build'
gyp ERR! System Linux 4.18.0-13-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/phiter/edex-ui/prebuild-src/node_modules/node-pty
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phiter/.npm/_logs/2018-12-24T10_59_39_308Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@1.1.2 prebuild-linux: `mkdir prebuild-src && cp -Rv src/* prebuild-src/ && node prebuild-minify.js && cd prebuild-src && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edex-ui@1.1.2 prebuild-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phiter/.npm/_logs/2018-12-24T10_59_39_408Z-debug.log
```

I have tried running `chmod -R 775 .` in the main dir, tried running NPM as root, opened the terminal as root, nothing works.

**Comment by phiter** [comment]
```
total 264
drwxr-xr-x   7 phiter phiter   4096 dez 24 09:29 .
drwxr-xr-x  53 phiter phiter   4096 dez 24 09:28 ..
-rw-r--r--   1 phiter phiter    657 dez 24 09:29 appveyor.yml
drwxr-xr-x   8 phiter phiter   4096 dez 24 09:29 .git
-rw-r--r--   1 phiter phiter    665 dez 24 09:29 .gitignore
-rw-r--r--   1 phiter phiter  35141 dez 24 09:29 LICENSE
drwxr-xr-x   3 phiter phiter   4096 dez 24 09:29 media
drwxr-xr-x 435 phiter phiter  16384 dez 24 09:29 node_modules
-rw-r--r--   1 phiter phiter   3672 dez 24 09:29 package.json
-rw-r--r--   1 phiter phiter 157564 dez 24 09:29 package-lock.json
-rw-r--r--   1 phiter phiter   3132 dez 24 09:29 prebuild-minify.js
drwxr-xr-x   5 root   root     4096 dez 24 09:30 prebuild-src
-rw-r--r--   1 phiter phiter   7784 dez 24 09:29 README.md
-rw-r--r--   1 phiter phiter    651 dez 24 09:29 .snyk
drwxr-xr-x   4 phiter phiter   4096 dez 24 09:29 src
-rw-r--r--   1 phiter phiter   1438 dez 24 09:29 .travis.yml
```

**Comment by GitSquared** [comment]
`prebuild-src` shouldn't be owned by `root`. You're running `npm run install-linux` as `phiter`, right? Not root/sudo?

**Comment by phiter** [comment]
Ok I changed the order of doing things and now the error is different. 
I was doing this:

```
clone
npm install
npm run build-linux
```
None of them ran as sudo.

Now I did this:

```
clone
npm install
npm run install-linux
npm start (to check if it works, it did)
npm run build-linux
```

build-linux is failing with this output:

```
> edex-ui@1.1.2 build-linux /home/phiter/edex-ui
> electron-builder build -l -p never

  • electron-builder version=20.38.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=4.0.0 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/eDEX-UI Linux (x86_64).AppImage
  • rebuilding native production dependencies platform=linux arch=ia32
Error: /usr/bin/node exited with code 1
Output:

> node-pty@0.8.0 install /home/phiter/edex-ui/prebuild-src/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/home/phiter/edex-ui/prebuild-src/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: Leaving directory '/home/phiter/edex-ui/prebuild-src/node_modules/node-pty/build'

Error output:
In file included from /usr/include/errno.h:25,
                 from /home/phiter/.electron-gyp/4.0.0/include/node/uv/errno.h:25,
                 from /home/phiter/.electron-gyp/4.0.0/include/node/uv.h:48,
                 from ../../nan/nan.h:50,
                 from ../src/unix/pty.cc:20:
/usr/include/features.h:424:12: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
            ^~~~~~~~~~~~~
compilation terminated.
make: *** [pty.target.mk:99: Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/phiter/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.0-13-generic
gyp ERR! command "/usr/bin/node" "/home/phiter/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/phiter/edex-ui/prebuild-src/node_modules/node-pty
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phiter/.npm/_logs/2018-12-24T11_40_18_417Z-debug.log

    at ChildProcess.childProcess.once.code (/home/phiter/edex-ui/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at rebuild (/home/phiter/edex-ui/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /home/phiter/edex-ui/node_modules/app-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at installOrRebuild (/home/phiter/edex-ui/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:511:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:472:70)
    at /home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:420:20
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (/home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/phiter/edex-ui/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/phiter/edex-ui/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/home/phiter/edex-ui/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/phiter/edex-ui/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/phiter/edex-ui/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/phiter/edex-ui/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@1.1.2 build-linux: `electron-builder build -l -p never`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edex-ui@1.1.2 build-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phiter/.npm/_logs/2018-12-24T11_40_47_007Z-debug.log
```

**Comment by phiter** [comment]
I'm trying to build it myself because of the fix you did yesterday for #361. If you could perhaps make another build with this fix and make it available It would be great.

**Comment by GitSquared** [comment]
We're getting there. You need some external build deps. This error is because you're missing `libc6-dev-i386`. Install it through apt.

OK, I won't release a new version just yet but I can give you a quick build if you want. Wait a sec.

**Comment by GitSquared** [comment]
@phiter [Here.](https://mega.nz/#!M1NlzCiD!Ps3plVAgGoU7zd3rJZZqZdw2uX8PMmN0EQQj1HW69AA)

Note that this is a dev version, should be pretty much bug-free but i can't guarantee anything.

**Comment by phiter** [comment]
I installed libc6 and now I have this one missing:

```
/usr/include/c++/8/bits/stl_algobase.h:59:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
```

My computer is used mainly for webdev so I don't have these libs. I'll wait for your build then XD

**Comment by GitSquared** [comment]
@phiter [Here.](https://mega.nz/#!M1NlzCiD!Ps3plVAgGoU7zd3rJZZqZdw2uX8PMmN0EQQj1HW69AA)

Note that this is a dev version, should be pretty much bug-free but i can't guarantee anything.

**Comment by phiter** [comment]
@GitSquared the issue on #361 is not working in this build. And I'm having this error:
![image](https://user-images.githubusercontent.com/12252332/50399044-8f5e7600-0763-11e9-9a89-30dcf04e203c.png)

**Comment by GitSquared** [comment]
@phiter [Is this any better?](https://mega.nz/#!g0dVwAKa!XHJA3ErrxjOCgAmVBBcPK4XqJHpkm3r29CICORBQaPE) I can't reproduce the Globe issue though.

**Comment by phiter** [comment]
The CTRL + TAB, CTRL + NUMBER issue is not fixed. 

The globe issue happens when I switch themes.

**Comment by GitSquared** [comment]
What the hell. Hold on.

**Comment by phiter** [comment]
I fixed my comment, the CTRL thing is working lmao

**Comment by GitSquared** [comment]
Ho OK, you scared me for a second lol. Gon look into the Globe one. Sorry for the trouble.

**Comment by phiter** [comment]
The globe error happens when I switch themes, but if I click panic nothing else happens.
I changed the theme on settings.json and I dind't have an error when I opened the application again.

Another thing I noticed is that if I put an invalid path on `cwd` in settings.json, the application will start opening and instantly crash, without informing what the problem is. Should this be opened as an issue to fix?

**Comment by phiter** [comment]
Damn you fixed all of them. You're fast, nice job!

**Comment by GitSquared** [comment]
Nice one with the `cwd` issue, I didn't think about that. I should add a bit more validation loops after parsing the settings... Hotfixed that one in the meantime.

The globe error was because of a commit i recently made to limit the framerate of the animation. When you switch themes, the globe is erased and re-created, but in this case the old code was still running for a few milliseconds and it tried to animate the old globe instance that doesn't exist anymore. Made it fail silently since it indeed does not have any consequences.

Also fixed the Nord theme because i just found out it didn't work properly while solving the other two issues.

[Updated build - hopefully this one will do!](https://mega.nz/#!w4VB2AAJ!d6Xkgk2s942w_oBX58Vnu99XK5kZnXVcmMvKyqLkD2M)

Thanks for your patience, lol. Normally I do a fuzz-testing and bug-fixing round before pushing a new release, but it didn't hurt doing it now.
