### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by huanghyw** [GitSquared/edex-ui#565]
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v2.2.3-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

```
➜  ~ git clone https://github.com/GitSquared/edex-ui.git
Cloning into 'edex-ui'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 5237 (delta 29), reused 0 (delta 0), pack-reused 5188
Receiving objects: 100% (5237/5237), 16.91 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (3724/3724), done.
➜  ~ cd edex-ui
➜  edex-ui git:(master) npm run install-linux


> edex-ui@2.2.3-pre install-linux /Users/huangyiwei/edex-ui
> npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..


> electron@4.2.8 postinstall /Users/huangyiwei/edex-ui/node_modules/electron
> node install.js

Downloading tmp-14648-1-SHASUMS256.txt-4.2.8
[============================================>] 100.0% of 4.74 kB (4.74 kB/s)
added 412 packages from 271 contributors and audited 1149 packages in 378.022s
found 0 vulnerabilities


> node-pty@0.8.1 install /Users/huangyiwei/edex-ui/src/node_modules/node-pty
> node scripts/install.js

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/huangyiwei/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:304:12)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:405:11)
gyp ERR! stack     at Socket.emit (events.js:196:13)
gyp ERR! stack     at Pipe.<anonymous> (net.js:586:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/huangyiwei/edex-ui/src/node_modules/node-pty
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huangyiwei/.npm/_logs/2019-08-15T03_56_31_712Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@2.2.3-pre install-linux: `npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edex-ui@2.2.3-pre install-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huangyiwei/.npm/_logs/2019-08-15T03_56_31_757Z-debug.log
```

**Comment by Chromecube** [comment]
`Command failed: /Users/huangyiwei/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];`

Seems like you have Anaconda installed and use this as your default python executable. Could you give me the output of `sys.version_info` from your python installation?

**Comment by GitSquared** [comment]
Closing; this is bad configuration on the user's side. Fix your python exec path and everything should work.
