### ISSUE TITLE
edex-ui is not opening in window 10 ?

### ISSUE THREAD

**Issue by vishal3063824** [GitSquared/edex-ui#610]
I'm using window 10. I downloaded edex-ui 2.2.2 and installed. But edex-ui is not opening in my system.

**Comment by Chromecube** [comment]
It would be super cool if you could provide some logs and further details to help understand your problem a bit better 😄

**Comment by GitSquared** [comment]
Try launching eDEX from a terminal (cmd/powershell) to get more detailed logs.

**Comment by GitSquared** [comment]
You might be experiencing the same issue as #611

**Comment by vishal3063824** [comment]
E-DeX is not even starting after so many try so how can I give any log
report. It even don't show any running task in task manager.

**Comment by GitSquared** [comment]
Launch the .exe from a cmd or powershell command line to get debug output.

**Comment by cryptotion** [comment]
Γû║  start     Starting eDEX-UI v2.2.2
i  info      With Node 10.11.0 and Electron 4.2.0
i  info      Renderer is Chrome 69.0.3497.128
Γû║  Startup   Initialized timer...
i  info      Base config dir is C:\Users\Krishna\AppData\Roaming\eDEX-UI
[ ]  pending   Loading settings file...
ΓêÜ  success   Settings loaded!
[ ]  pending   Creating new terminal process on port 3000
(node:4868) UnhandledPromiseRejectionWarning: Error: File not found:
    at new WindowsPtyAgent (C:\Users\Krishna\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:53:36)
    at new WindowsTerminal (C:\Users\Krishna\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\Krishna\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at new Terminal (C:\Users\Krishna\AppData\Local\Programs\edex-ui\resources\app.asar\classes\terminal.class.js:1:8188)
    at App.app.on (C:\Users\Krishna\AppData\Local\Programs\edex-ui\resources\app.asar\_boot.js:181:11)
(node:4868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


> Launch the .exe from a cmd or powershell command line to get debug output.
