### ISSUE TITLE
Cannot start on win 10

### ISSUE THREAD

**Issue by Ladvace** [GitSquared/edex-ui#736]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

When I run it via command line I recive this error:

```
[ ]  pending   Creating new terminal process on port 3000
(node:8004) UnhandledPromiseRejectionWarning: Error: File not found:
    at new WindowsPtyAgent (C:\Users\caval\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:50:36)
    at new WindowsTerminal (C:\Users\caval\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\caval\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at new Terminal (C:\Users\caval\AppData\Local\Programs\edex-ui\resources\app.asar\classes\terminal.class.js:1:8188)
    at App.app.on (C:\Users\caval\AppData\Local\Programs\edex-ui\resources\app.asar\_boot.js:181:11)
(node:8004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

(Write your report here)

**Comment by GitSquared** [comment]
Check what `shell` is specified in the settings (check github wiki for config location etc). Try changing that to another program, or perhaps specifying the full absolute path to the shell binary.

**Comment by Ladvace** [comment]
thanks, I solved
