### ISSUE TITLE
Crash/Hang on Centos 7

### ISSUE THREAD

**Issue by Vanscot** [GitSquared/edex-ui#808]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [X] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Downloaded the v2.2.2 AppImage file to try this UI but I run into this:
```
./eDEX-UI.Linux.x86_64.AppImage
▶  start     Starting eDEX-UI v2.2.2
ℹ  info      With Node 10.11.0 and Electron 4.2.0
ℹ  info      Renderer is Chrome 69.0.3497.128
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/andregon/.config/eDEX-UI
☐  pending   Loading settings file...
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
(node:14547) UnhandledPromiseRejectionWarning: Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/tmp/.mount_eDEX-Ubc7BYn/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.loadNative (/tmp/.mount_eDEX-Ubc7BYn/resources/app.asar/node_modules/node-pty/lib/utils.js:22:16)
    at Object.<anonymous> (/tmp/.mount_eDEX-Ubc7BYn/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:24:19)
    at Object.<anonymous> (/tmp/.mount_eDEX-Ubc7BYn/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:255:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
(node:14547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Seems like the app is running/trying to run as I can get some pids if I run ps aux | grep -i edex but it just hangs in there and nothing happens.

```
andregon 14547  0.3  0.3 1140476 59980 pts/2   Sl+  14:47   0:00 /tmp/.mount_eDEX-Ubc7BYn/edex-ui
andregon 14551  9.9  0.0  24012  2944 ?        Ssl  14:47   0:12 ./eDEX-UI.Linux.x86_64.AppImage
andregon 14567  0.0  0.1 474040 24200 pts/2    S+   14:47   0:00 /tmp/.mount_eDEX-Ubc7BYn/edex-ui --type=zygote --no-sandbox
andregon 14595  0.0  0.2 556552 41804 pts/2    Sl+  14:48   0:00 /tmp/.mount_eDEX-Ubc7BYn/edex-ui --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAA AAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=15260943900039198947
andregon 14892  0.0  0.0 112836   992 pts/3    S+   14:49   0:00 grep --color=auto -i edex
```
System Specs:
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 cores/threads)
16GB of RAM
Intel Corporation UHD Graphics 620 (rev 07) + NVIDIA Corporation GM108M [GeForce MX130] (rev a2)
Centos 7 (up to date)

If you need more info, let me know so I can provide it.

**Comment by Vanscot** [comment]
> Looks like some native dependency fucked up. You should try running from source (see readme), and you'll also get a way more updated version (400+ commits).

Will do and report back.

**Comment by Vanscot** [comment]
Failed again. Default versions on Centos 7 are kind of old: npm 3.10.10-1.6.17.1.1.el7, nodejs 6.17.1-1.el7
Official repo (nodesource) versions are: npm 7.0.7, nodejs v15.0.1

Output was
```
npm run install-linux

> edex-ui@3.0.0-pre install-linux
> npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..


> edex-ui@3.0.0-pre prepare
> npm run snyk-protect


> edex-ui@3.0.0-pre snyk-protect
> snyk protect

Successfully applied Snyk patches


added 765 packages, and audited 765 packages in 9s

found 0 vulnerabilities
npm ERR! code 1
npm ERR! path /home/andregon/.local/sources/edex-ui/src/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! make: se ingresa al directorio `/home/andregon/.local/sources/edex-ui/src/node_modules/node-pty/build'
npm ERR!   CXX(target) Release/obj.target/pty/src/unix/pty.o
npm ERR! make: se sale del directorio `/home/andregon/.local/sources/edex-ui/src/node_modules/node-pty/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@6.1.0
npm ERR! gyp info using node@15.0.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/andregon/.local/sources/edex-ui/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/andregon/.local/sources/edex-ui/src/node_modules/node-pty/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/andregon/.local/sources/edex-ui/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/andregon/.cache/node-gyp/15.0.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/andregon/.cache/node-gyp/15.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/andregon/.local/sources/edex-ui/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/andregon/.cache/node-gyp/15.0.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/andregon/.local/sources/edex-ui/src/node_modules/node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from /home/andregon/.cache/node-gyp/15.0.1/include/node/node.h:67:0,
npm ERR!                  from ../../nan/nan.h:54,
npm ERR!                  from ../src/unix/pty.cc:20:
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h: En la función miembro ‘void v8::TracedReferenceBase<T>::SetSlotThreadSafe(T*)’:
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:912:22: error: se esperaba un especificador de tipo
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:912:22: error: se esperaba ‘>’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:912:22: error: se esperaba ‘(’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:912:22: error: ‘atomic’ no es un miembro de ‘std’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:912:35: error: expected primary-expression before ‘*’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                    ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:912:36: error: expected primary-expression before ‘>’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                     ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:912:38: error: expected primary-expression before ‘>’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:913:54: error: ‘memory_order_relaxed’ no es un miembro de ‘std’
npm ERR!                                                       std::memory_order_relaxed);
npm ERR!                                                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:913:80: error: expected ‘)’ before ‘;’ token
npm ERR!                                                       std::memory_order_relaxed);
npm ERR!                                                                                 ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h: En la función miembro ‘const T* v8::TracedReferenceBase<T>::GetSlotThreadSafe() const’:
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:29: error: se esperaba un especificador de tipo
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                              ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:29: error: se esperaba ‘>’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:29: error: se esperaba ‘(’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:29: error: ‘atomic’ no es un miembro de ‘std’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:41: error: expected primary-expression before ‘const’
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                                          ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:41: error: expected ‘)’ before ‘const’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:41: error: expected ‘;’ before ‘const’
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:49: error: expected unqualified-id before ‘>’ token
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                                                  ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:920:49: error: expected initializer before ‘>’ token
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h: En el ámbito global:
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:1631:58: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!                                  Local<Value> export_value);
npm ERR!                                                           ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:3405:23: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    Local<Value> Name() const { return Description(); }
npm ERR!                        ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5216:76: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5263:21: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    bool IsExternal() const;
npm ERR!                      ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5290:24: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    Contents Externalize();
npm ERR!                         ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5300:70: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void Externalize(const std::shared_ptr<BackingStore>& backing_store);
npm ERR!                                                                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5311:24: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    Contents GetContents();
npm ERR!                         ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5699:76: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5748:76: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5757:21: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    bool IsExternal() const;
npm ERR!                      ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5773:24: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    Contents Externalize();
npm ERR!                         ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5783:70: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void Externalize(const std::shared_ptr<BackingStore>& backing_store);
npm ERR!                                                                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:5798:24: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    Contents GetContents();
npm ERR!                         ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7143:28: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    size_t code_range_size() const { return code_range_size_ / kMB; }
npm ERR!                             ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7145:46: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void set_code_range_size(size_t limit_in_mb) {
npm ERR!                                               ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7149:38: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    size_t max_semi_space_size_in_kb() const;
npm ERR!                                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7151:56: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void set_max_semi_space_size_in_kb(size_t limit_in_kb);
npm ERR!                                                         ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7153:31: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    size_t max_old_space_size() const { return max_old_generation_size_ / kMB; }
npm ERR!                                ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7155:49: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void set_max_old_space_size(size_t limit_in_mb) {
npm ERR!                                                  ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7159:31: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    size_t max_zone_pool_size() const { return max_zone_pool_size_; }
npm ERR!                                ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:7161:43: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void set_max_zone_pool_size(size_t bytes) { max_zone_pool_size_ = bytes; }
npm ERR!                                            ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:8751:59: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!                                      MeasureMemoryMode mode);
npm ERR!                                                            ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:8814:36: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    Local<Context> GetEnteredContext();
npm ERR!                                     ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:9098:22: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void RunMicrotasks() { PerformMicrotaskCheckpoint(); }
npm ERR!                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:9142:75: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
npm ERR!                                                                            ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:9150:78: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
npm ERR!                                                                               ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:9334:30: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    UnwindState GetUnwindState();
npm ERR!                               ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:9397:54: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!        AllowCodeGenerationFromStringsCallback callback);
npm ERR!                                                       ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:9757:75: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    static bool TryHandleSignal(int signal_number, void* info, void* context);
npm ERR!                                                                            ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:10713:55: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!                                  const void* stack_base);
npm ERR!                                                        ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/v8.h:10739:65: aviso: se descarta la directiva de atributo ‘deprecated’ [-Wattributes]
npm ERR!    static bool PCIsInV8(const UnwindState& unwind_state, void* pc);
npm ERR!                                                                  ^
npm ERR! In file included from ../../nan/nan.h:54:0,
npm ERR!                  from ../src/unix/pty.cc:20:
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/node.h: En la función lambda:
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/node.h:617:43: error: no se expanden los paquetes de parámetro con ‘...’
npm ERR!              std::forward<EnvironmentArgs>(env_args)...);
npm ERR!                                            ^
npm ERR! /home/andregon/.cache/node-gyp/15.0.1/include/node/node.h:617:43: nota:         ‘env_args’
npm ERR! make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/andregon/.local/sources/edex-ui/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
npm ERR! gyp ERR! System Linux 3.10.0-1127.19.1.el7.x86_64
npm ERR! gyp ERR! command "/usr/bin/node" "/home/andregon/.local/sources/edex-ui/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/andregon/.local/sources/edex-ui/src/node_modules/node-pty
npm ERR! gyp ERR! node -v v15.0.1
npm ERR! gyp ERR! node-gyp -v v6.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andregon/.npm/_logs/2020-11-02T20_53_25_565Z-debug.log
npm ERR! code 1
npm ERR! path /home/andregon/.local/sources/edex-ui
npm ERR! command failed
npm ERR! command sh -c npm install && cd src && npm install && ./../node_modules/.bin/electron-rebuild -f -w node-pty && cd ..

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andregon/.npm/_logs/2020-11-02T20_53_25_605Z-debug.log
```

After running:
```
npm cache clear --force
npm install n
npm install snyk
```
And letting it sit for 5 minutes (seriously) finally worked.
I did run into the "[7222:1102/180112.165286:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now." message but nothing that I couldn't manage.
Still, I'm running a multi-display setup and it only uses the primary display (laptop display in my case) no matter where I run the command. Network stats aren't working (using NetworkManager here, and openvpn). Endpoint Lat/Long and ip (using dhcp) don't work either. Aside from that, only the settings window is a bit too tall and part of the buttons are lost at the bottom. 

Really nice work!

**Comment by GitSquared** [comment]
> Still, I'm running a multi-display setup and it only uses the primary display (laptop display in my case) no matter where I run the command.

Check out the `monitor` option in the settings!
