### ISSUE TITLE
edex-ui not showing then crash on quit

### ISSUE THREAD

**Issue by anakojm** [GitSquared/edex-ui#874]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

![gif](https://media4.giphy.com/media/uQqbAI9Hr4z93J4TFc/giphy.gif)
I'm on catalina but I had the same issue on mojave and high sierra.
When I launch the app in whatever way (sudo, compiling from source, opening the executable...), nothing appen, then, when I quit the app, I get an error message.

### Logs
```
npm start   

> edex-ui@3.0.0-pre start /Users/Anako/edex-ui
> electron src --nointro

▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.1.5
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /Users/anako/Library/Application Support/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
✖  fatal     TypeError: Cannot read property 'close' of undefined
    at App.<anonymous> (/Users/Anako/edex-ui/src/_boot.js:360:9)
    at App.emit (events.js:310:20)
(node:89641) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/bash -ilc echo -n "_SHELL_ENV_DELIMITER_"; env; echo -n "_SHELL_ENV_DELIMITER_"; exit
bash: no job control in this shell


    at makeError (/Users/Anako/edex-ui/src/node_modules/shell-env/node_modules/execa/index.js:174:9)
    at /Users/Anako/edex-ui/src/node_modules/shell-env/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/Users/Anako/edex-ui/src/node_modules/shell-env/index.js:29:20)
    at async App.<anonymous> (/Users/Anako/edex-ui/src/_boot.js:226:20)
(node:89641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:89641) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@3.0.0-pre start: `electron src --nointro`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edex-ui@3.0.0-pre start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anako/.npm/_logs/2020-11-09T16_12_31_729Z-debug.log
```
output of /Users/anako/.npm/_logs/2020-11-09T16_12_31_729Z-debug.log :

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle edex-ui@3.0.0-pre~prestart: edex-ui@3.0.0-pre
6 info lifecycle edex-ui@3.0.0-pre~start: edex-ui@3.0.0-pre
7 verbose lifecycle edex-ui@3.0.0-pre~start: unsafe-perm in lifecycle true
8 verbose lifecycle edex-ui@3.0.0-pre~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Anako/edex-ui/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/Anako/opt/miniconda3/bin:/Users/anako/.gem/ruby/2.7.0/bin:/Applications/LibreOffice.app/Contents/MacOS:/usr/local/opt/libpcap/bin:/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/local/opt/sqlite/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/libarchive/bin:/Users/Anako/perl5/bin:/usr/local/opt/nss/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/Anako/.rvm/gems/ruby-2.2.1/bin:/Users/Anako/.rvm/gems/ruby-2.2.1@global/bin:/Users/Anako/.rvm/rubies/ruby-2.2.1/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/Anako/.rvm/bin:/Users/Anako/.vimpkg/bin:/Users/Anako/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/Anako/.antigen/bundles/supercrabtree/k:/Users/Anako/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sudo:/Users/Anako/.antigen/bundles/gretzky/auto-color-ls:/Users/Anako/.antigen/bundles/MichaelAquilina/zsh-you-should-use:/Users/Anako/.antigen/bundles/romkatv/powerlevel10k:/bin:/usr/local/opt/go/libexec/bin:/Users/anako/go/bin
9 verbose lifecycle edex-ui@3.0.0-pre~start: CWD: /Users/Anako/edex-ui
10 silly lifecycle edex-ui@3.0.0-pre~start: Args: [ '-c', 'electron src --nointro' ]
11 silly lifecycle edex-ui@3.0.0-pre~start: Returned: code: 1  signal: null
12 info lifecycle edex-ui@3.0.0-pre~start: Failed to exec start script
13 verbose stack Error: edex-ui@3.0.0-pre start: `electron src --nointro`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid edex-ui@3.0.0-pre
15 verbose cwd /Users/Anako/edex-ui
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error edex-ui@3.0.0-pre start: `electron src --nointro`
22 error Exit status 1
23 error Failed at the edex-ui@3.0.0-pre start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by GitSquared** [comment]
> `bash: no job control in this shell`

You should figure out how to enable that. Most shells have job control enabled by default, I'm not exactly sure why yours is off - but edex is trying to leverage those features for some data that's displayed on screen and it needs jobs to work.

**Comment by anakojm** [comment]
The issue was in my end, I had to remove `exec zsh` from my bashrc which was executing zsh when executing bash, zsh doesn't seems to have job control enabled by default.
I ran in another issue wich was that edex-ui was using bash where my default shell is zsh and that there where color in bash prommpt but not in zsh.
<img width="948" alt="Screen Shot 2020-11-22 at 12 23 28" src="https://user-images.githubusercontent.com/49002220/99902353-8cf15780-2cbd-11eb-8ac0-29eeb748b745.png">

**Comment by GitSquared** [comment]
Glad you could figure this out. Cool prompt by the way 😎
