### ISSUE TITLE
Error: Cannot find module '../build/Debug/pty.node'

### ISSUE THREAD

**Issue by eddy-resnick** [GitSquared/edex-ui#889]
## Technical information
**Using version:**
 - [X ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [S ] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

$ ./eDEX-UI.Linux.x86_64.AppImage 
[16889:1112/191118.469189:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_eDEX-UUNNX1M/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

$ ./eDEX-UI.Linux.x86_64.AppImage -no-sandbox
▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.1.5
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/eddy/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-UAwhZW8/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-UAwhZW8/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-UAwhZW8/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-UAwhZW8/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UAwhZW8/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-UAwhZW8/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-UAwhZW8/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-UAwhZW8/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-UAwhZW8/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:16925) UnhandledPromiseRejectionWarning: Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.Sl7i0K)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UAwhZW8/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:16925) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16925) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

^C
$ npm version
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.8.0',
  icu: '50.1.2',
  modules: '48',
  napi: '3',
  node: '6.17.1',
  openssl: '1.0.2k-fips',
  uv: '1.40.0',
  v8: '5.1.281.111',
  zlib: '1.2.7' }

**Comment by GitSquared** [comment]
> Error: /lib64/libc.so.6: version GLIBC_2.28'

You should try to install glibc2!

Regarding the sandbox issue, check #588 and especially [this comment](https://github.com/GitSquared/edex-ui/issues/588#issuecomment-538114654).
