### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by redbrain** [GitSquared/edex-ui#926]
I tried to build eDEX-UI as a snap package; it doesn't work on launch. (I just changed the build-linux command to target snap)
Here's console output upon running `edex-ui`:
```
▶  start     Starting eDEX-UI v2.2.3
ℹ  info      With Node 12.16.3 and Electron 10.1.6
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/redbrain/snap/edex-ui/x1/.config/eDEX-UI
☐  pending   Mirroring internal assets...
Gtk-Message: 15:09:28.463: Failed to load module "colorreload-gtk-module"
Gtk-Message: 15:09:28.464: Failed to load module "appmenu-gtk-module"
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
/usr/share/libdrm/amdgpu.ids: No such file or directory
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /snap/edex-ui/x1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /snap/edex-ui/x1/resources/app.asar/node_modules/node-pty/lib/index.js
- /snap/edex-ui/x1/resources/app.asar/classes/terminal.class.js
- /snap/edex-ui/x1/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snap/edex-ui/x1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snap/edex-ui/x1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/snap/edex-ui/x1/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/snap/edex-ui/x1/resources/app.asar/classes/terminal.class.js',
    '/snap/edex-ui/x1/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:248778) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /run/user/1000/snap.edex-ui/.org.chromium.Chromium.SXsKhZ)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snap/edex-ui/x1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:248778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:248778) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Is there a way to fix this, and thus be able to install eDEX-UI as a snap?
Thanks for your help in advance; and a thank you to GitSquared specifically because this project is cool :)

**Comment by redbrain** [comment]
Luckily I'm no longer confined to a snap; now using .deb and it's fine.
