### ISSUE TITLE
AppImage does not run

### ISSUE THREAD

**Issue by probonopd** [GitSquared/edex-ui#99]
Getting 

```
module.js:545
    throw err;
    ^
Error: Cannot find module '/run/firejail/appimage/.appimage-6898/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Parent pid 6898, child pid 6901
Parent is shutting down, bye...
```

on Ubuntu 14.04.

Reference:
https://github.com/AppImage/appimage.github.io/pull/611

**Comment by GitSquared** [comment]
Can reproduce on my Debian 9 system. I'll try rolling back electron-builder to v20.14.7 as suggested in electron-userland/electron-builder/issues/2958 and see if the appImage works.

**Comment by GitSquared** [comment]
I will keep an eye on the upstream issue to update electron-builder back when the issue is closed. The AppImage assets in this repo's releases will get updated in a minute.

**Comment by probonopd** [comment]
Thanks, the workaround seems to work.

**Comment by GitSquared** [comment]
Update: the upstream issue has been resolved and electron-builder has been updated.
