### ISSUE TITLE
2.2.5 doesn't run on OpenSUSE 15.1

### ISSUE THREAD

**Issue by lapsio** [GitSquared/edex-ui#997]
I'm getting following error and app doesn't start:
```
lapsio@linux-a7l6 ~> ./eDEX-UI-Linux-x86_64.AppImage 
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/lapsio/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-Uamt957/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-Uamt957/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-Uamt957/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-Uamt957/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-Uamt957/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-Uamt957/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-Uamt957/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-Uamt957/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-Uamt957/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:16010) UnhandledPromiseRejectionWarning: Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.gNMNdG)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-Uamt957/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:16010) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16010) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wrac4242** [comment]
hey, you need the packages needed for building installed, as it is complaining about g lib c. For openSUSE, according to a quick google devel_basis and openssl-devel are the packages you need

**Comment by lapsio** [comment]
> hey, you need the packages needed for building installed, as it is complaining about g lib c. For openSUSE, according to a quick google devel_basis and openssl-devel are the packages you need

There's no such packages for OpenSUSE. Yes I do have libopenssl-devel package. This error is due to fact that app is compiled for too new glibc version. The highest available glibc version on OpenSUSE 15.1 is 2.26 yet your app requires 2.28 which is unrealistically high requirement for anything other than rolling distro. In fact even OpenSUSE Tumbleweed which is rolling distribution only has 2.26 in repo available as of now. CentOS 7 for example supports only up to 2.17.

**Comment by wrac4242** [comment]
can you try to run from source then, as it may be just that dependency that is out of date

**Comment by GitSquared** [comment]
We do not aim to support *every* linux distro as especially in the Linux world system details and libraries versions vary a lot as I'm sure you know. That said, we do have CI builds on libc 2.27, you can download artifacts here: https://github.com/GitSquared/edex-ui/suites/1748097370/artifacts/33217538
